# Generated by Django 5.0.4 on 2024-05-02 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Channels')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='channel_images')),
            ],
        ),
        migrations.CreateModel(
            name='TVShows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='TVShows')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='tvshow_images')),
            ],
        ),
        migrations.CreateModel(
            name='TVShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('duration', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.channels')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tvshows')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tvshowtime')),
            ],
        ),
        migrations.AddField(
            model_name='channels',
            name='shows',
            field=models.ManyToManyField(through='main.ChannelShowTime', to='main.tvshows'),
        ),
    ]
