# Generated by Django 5.0.4 on 2024-05-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelshowtime',
            name='time',
        ),
        migrations.AlterModelOptions(
            name='channels',
            options={'verbose_name': 'Channel', 'verbose_name_plural': 'Channels'},
        ),
        migrations.AlterModelOptions(
            name='tvshows',
            options={'verbose_name': 'TVShow', 'verbose_name_plural': 'TVShows'},
        ),
        migrations.AddField(
            model_name='channelshowtime',
            name='duration',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='channelshowtime',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='channels',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tvshows',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='TVShowTime',
        ),
    ]
