# Generated by Django 5.0.4 on 2024-05-06 08:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_channelshowtime_time_alter_channels_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelshowtime',
            name='start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
