# Generated by Django 5.0.4 on 2024-05-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_channelshowtime_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channels',
            name='shows',
        ),
    ]
