# Generated by Django 5.0.4 on 2024-05-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_channels_shows'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshows',
            name='category',
            field=models.CharField(blank=True, choices=[('DR', 'Drama'), ('CM', 'Comedy'), ('AC', 'Action'), ('SF', 'Science Fiction'), ('RM', 'Romance'), ('TH', 'Thriller'), ('AD', 'Adventure')], max_length=2, null=True),
        ),
    ]
