# Generated by Django 5.0.4 on 2024-05-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tvshows_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshows',
            name='category',
            field=models.CharField(blank=True, choices=[('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Science Fiction', 'Science Fiction'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Adventure', 'Adventure')], max_length=20, null=True),
        ),
    ]
